const b = {
	"navList": [{
		"name": "首页",
		"r": "home",
		"show": true,
		"p": "",
		"select": true,
		"type": 1,
		"b": {},
		"a": false,
		"m": []
	}],
	"layout":{
		"bannerShow":'1',
		"bannerbgc":'#303133',
		"bannerbgcType":'2',
		"bannerHeight":50,
		"navShow":'1',
		"navHeight":40,
		"navbgc":'#ffffff',
		"navbgcType":'2',
		"navfdc":'#000000',
		"navfdct":'2',
		"navfac":'#409EFF',
		"navfact":'2',
		"navFs":'16',
		"navItemWidth":'120',
		"navPosition":'j-c-s',
		"navStyle":'1',
		"navMenuFold":'2',
		"foldSize":30,
		"foldfdc":'#000000',
		"foldfdct":'2',
		"sideWidth":'12',
		"sidebgc":'#ffffff',
		"sidebgcType":'2',
		"sideItemHeight":56,
		"sideFs":'14',
		"sidefsc":'#303133',
		"sidefsct":'2',
		"sidefsac":'#FFD04B',
		"sidefsact":'2',
		"sidefsmc":'#F2F6FC',
		"sidefsmct":'2',
		"mainMt":'10',
		"mainMr":'0',
		"mainMl":'0',
		"mainMb":'0',
		"mainRtHeight":'44',
		"mainRtMt":'0',
		"mainRtMr":'10',
		"mainRtMb":'10',
		"mainRtMl":'10',
		"mainRtbgc":'#ffffff',
		"mainRtbgct":'2',
		"mainRtBrlt":'6',
		"mainRtBrlb":'6',
		"mainRtBrrt":'6',
		"mainRtBrrb":'6',
		"mainRtSd":'1',
		"mainRtSdc":'#d1d9e6',
		"mainRtSdct":'2',
		"mainRtuSd":'2',
		"mainRtSdV":4,
		"mainRtSdR":2,
		"mainRtSdS":'5',
		"mainRtSdL":1,
		"mainRtFs":'18',
		"mainCwMt":'0',
		"mainCwMr":'5',
		"mainCwMl":'5',
		"mainCwMb":'0',
		"mainCpMt":'0',
		"mainCpMr":'5',
		"mainCpMb":'10',
		"mainCpMl":'5',
		"mainCpbgc":'#ffffff',
		"mainCpbgct":'2',
		"mainCpBrlt":'6',
		"mainCpBrlb":'6',
		"mainCpBrrt":'6',
		"mainCpBrrb":'6',
		"mainCpSd":'1',
		"mainCpSdc":'#d1d9e6',
		"mainCpSdct":'2',
		"mainCpuSd":'2',
		"mainCpSdV":4,
		"mainCpSdR":2,
		"mainCpSdS":'5',
		"mainCpSdL":1,
		"mainCpFs":'18',
		"sysName":'Sayho智能后台管理系统',
		"sysNameShow":'1',
		"sysNameFs":'18',
		"sysNameMl":'0',
		"sysNameMr":'0',
		"sysNameColor":'#ffffff',
		"sysNameColorType":'2',
		"sysIconShow":'1',
		"sysIconSource":'1',
		"routeOrhost":'/images/',
		"sysIcon":'banner.png',
		"sysIconHeight":'32',
		"sysIconMl":'10',
		"sysIconMr":'10',
		"sysbgc":'#f2f2f2',
		"sysbgct":'2',
	},
	"pageInfo":{
		"pagebgct":'1',
		"pagebgc":'#242528',
		"pagebgcopa":10,
		"pagebghost":'/images/',
		"pagebgpic":'',
		"pageHaS":'2',
		"pageHaHeight":60,
		"pageNav":[{
			"id":0,
			"name":'首页',
			"r":'home',
			"content":[{
				"type":'1',
				"contWidth":'500',
				"contLabWidth":'100',
				"contbgct":'1',
				"contbgc":'#ffffff',
				"contbgcopa":0,
				"contbghost":'/images/',
				"contbgpic":'',
				"contMt":'10',
				"contMr":'50',
				"contMl":'50',
				"contMb":'10',
				"contBrlt":'6',
				"contBrlb":'6',
				"contBrrt":'6',
				"contBrrb":'6',
				"contSd":'1',
				"contSdc":'#1C1C1E',
				"contSdct":'2',
				"contuSd":'1',
				"contSdV":4,
				"contSdR":2,
				"contSdS":'5',
				"contSdL":1,
				"labelList":[{
					"label":'Welcome to Sayho',
					"attr":'title',
					"type":'text',
					"labelFp":'center',
					"labelFw":'1',
					"labelFs":'22',
					"labelFc":'#ffffff',
					"labelWidt":'1',
					"labelMt":'22',
					"labelMr":'10',
					"labelMl":'10',
					"labelMb":'22',
				},{
					"label":'账号',
					"attr":'username',
					"type":'input',
					"labelFs":'14',
					"labelFc":'#242528',
					"labelMt":'0',
					"labelMr":'10',
					"labelMl":'10',
					"labelMb":'22',
					"labelBrlt":'6',
					"labelBrlb":'6',
					"labelBrrt":'6',
					"labelBrrb":'6',
				},{
					"label":'密码',
					"attr":'password',
					"type":'input',
					"labelFs":'14',
					"labelFc":'#242528',
					"labelMt":'0',
					"labelMr":'10',
					"labelMl":'10',
					"labelMb":'22',
					"labelBrlt":'6',
					"labelBrlb":'6',
					"labelBrrt":'6',
					"labelBrrb":'6',
				},{
					"label":'验证码',
					"attr":'code',
					"type":'input',
					"labelFs":'14',
					"labelFc":'#242528',
					"labelMt":'0',
					"labelMr":'10',
					"labelMl":'10',
					"labelMb":'22',
					"labelBrlt":'6',
					"labelBrlb":'6',
					"labelBrrt":'6',
					"labelBrrb":'6',
				},{
					"label":'Login',
					"attr":'submit',
					"type":'button',
					"labelWidt":'2',
					"labelWid":'80',
					"labelFs":'14',
					"labelFc":'#ffffff',
					"labelMt":'0',
					"labelMr":'10',
					"labelMl":'10',
					"labelMb":'10',
					"labelBgc":'#409EFF',
					"labelBgct":'2',
					"labelBrlt":'6',
					"labelBrlb":'6',
					"labelBrrt":'6',
					"labelBrrb":'6',
				}],
			}]
		}],
		"pageFaS":'2',
		"pageFaHeight":60,
	},
	"apiList": [],
	"config": {
		"host": [
			{
				"name": "",
				"env": [
					{
						"name": "绑定投产站点地址",
						"type": "publish",
						"url": ""
					},
					{
						"name": "绑定测试站点地址",
						"type": "test",
						"url": ""
					}
				]
			}
		],
		"ajaxConfig": {
			"useHeader": "1",
			"backInfo":"2",
			"headerList": [
				{
					"p": "Accept",
					"type": "1",
					"value": "application/json,text/plain,*/*"
				},
				{
					"p": "Content-Type",
					"type": "1",
					"value": "application/json;charset=UTF-8"
				},
				{
					"p": "Accept-Language",
					"type": "1",
					"value": "zh-CN,zh;q=0.9,en;q=0.8,ja;q=0.7"
				}
			]
		},
		"store":[],
		"hostEnvPoint":"publish"
	},
}
